### ISSUE TITLE
Performance: add index on tt_content.list_type

### ISSUE THREAD

**Issue by dogawaf** [pluswerk/cache_automation#9]
For performance gain when saving a record in the backend, an SQL index on tt_content.list_type can help on huge websites.

In `ext_tables.sql`:
```
#
# Table structure for table 'tt_content'
#
CREATE TABLE tt_content (
	INDEX index_list_type(list_type)
);
```

**Comment by Kanti** [comment]
Hi @dogawaf,

this change seems to be a good addition to the Extension.
Can you create a Pull Request for this change?
